In [1]:
for x in range(2002,3200,7):
    if x % 5 != 0:
        print(x)

2002
2009
2016
2023
2037
2044
2051
2058
2072
2079
2086
2093
2107
2114
2121
2128
2142
2149
2156
2163
2177
2184
2191
2198
2212
2219
2226
2233
2247
2254
2261
2268
2282
2289
2296
2303
2317
2324
2331
2338
2352
2359
2366
2373
2387
2394
2401
2408
2422
2429
2436
2443
2457
2464
2471
2478
2492
2499
2506
2513
2527
2534
2541
2548
2562
2569
2576
2583
2597
2604
2611
2618
2632
2639
2646
2653
2667
2674
2681
2688
2702
2709
2716
2723
2737
2744
2751
2758
2772
2779
2786
2793
2807
2814
2821
2828
2842
2849
2856
2863
2877
2884
2891
2898
2912
2919
2926
2933
2947
2954
2961
2968
2982
2989
2996
3003
3017
3024
3031
3038
3052
3059
3066
3073
3087
3094
3101
3108
3122
3129
3136
3143
3157
3164
3171
3178
3192
3199


In [2]:
x = int(input())
y = 1
while x > 1:
    y = y * x
    x = x - 1
print(y)

8
40320


In [3]:
x = int(input())
Dict = {1:1}
y = 1
while y < x:
    y = y + 1 
    Dict[y]=y*y
print(Dict)

8
{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64}


In [4]:
import pandas as pd 
import math
s = input()
D = s.split(",")
Ds = ""
for x in D:
    if x == D[0]:
        Q = math.sqrt((2*50*int(x))/30)
        Ds = str(int(Q))
    else:
        Q = math.sqrt((2*50*int(x))/30)
        Ds = Ds + "," + str(int(Q))
print(Ds)

100,150,180
18,22,24


In [5]:
s = input()
n = int(input())
L = s.split(s[n])
print(L[0]+L[1])

kitten
1
ktten


In [9]:
s = input()
s1=""
for x in range(0,len(s)):
    if s[x]=="y":
        s1 = s1 + "a"
    elif s[x]=="z":
        s1 = s1 + "b"
    elif s[x]==" " or s[x]== "." or s[x]=="'" or s[x]=="(" or s[x]==")":
        s1 = s1 + s[x]
    else:
        s1 = s1 + chr(ord(s[x])+2)
print(s1)

g fmnc wms bgblr rpylqjyrc gr zw fylb. rfyrq ufyr amknsrcpq ypc dmp. bmgle gr gl zw fylb gq glcddgagclr ylb rfyr'q ufw rfgq rcvr gq qm jmle. sqgle qrpgle.kyicrpylq() gq pcamkkclbcb. lmu ynnjw ml rfc spj.
i hope you didnt translate it by hand. thats what computers are for. doing it in by hand is inefficient and that's why this text is so long. using string.maketrans() is recommended. now apply on the url.


In [1]:
import numpy as np
ar = np.array(input())
print("Original array elements: ",ar)
print("Array to list: ",ar.tolist())

[[0 1] [2 3] [4 5]] 
Original array elements:  [[0 1] [2 3] [4 5]] 
Array to list:  [[0 1] [2 3] [4 5]] 


In [2]:
import numpy as np 
a1= np.array(input())
a2= np.array(input())
ar= np.concatenate((a1, a2), axis=0)
print(np.cov(ar))

[0 1 2] 
[2 1 0]


ValueError: zero-dimensional arrays cannot be concatenated